name: Publish

on:
  push:
    branches:
      - md

jobs:
  build:

      runs-on: ubuntu-latest

    steps:
     - name: generate update
       run: |
        wget ${{secrets.PUBLISH_URL}}